name: Deploy to Google Apps Script

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Push code using clasp
        uses: daikikatsuragawa/clasp-action@v1.2.0
        with:
          accessToken: ${{ secrets.ACCESS_TOKEN }}
          idToken: ${{ secrets.ID_TOKEN }}
          refreshToken: ${{ secrets.REFRESH_TOKEN }}
          clientId: ${{ secrets.CLIENT_ID }}
          clientSecret: ${{ secrets.CLIENT_SECRET }}
          command: 'push'
