name: Deploy to Google Apps Script

on:
  workflow_run:
    workflows: ["Lint"]
    types:
      - completed
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Push code using clasp (Personal Project)
        uses: lucienve/clasp-action@v1.2.1
        with:
          accessToken: ${{ secrets.ACCESS_TOKEN }}
          idToken: ${{ secrets.ID_TOKEN }}
          refreshToken: ${{ secrets.REFRESH_TOKEN }}
          clientId: ${{ secrets.CLIENT_ID }}
          clientSecret: ${{ secrets.CLIENT_SECRET }}
          scriptId: ${{ secrets.SCRIPT_ID }}
          command: 'push'

      - name: Push code using clasp (Template Project)
        if: ${{ env.TEMPLATE_SCRIPT_ID != '' }}
        env:
          TEMPLATE_SCRIPT_ID: ${{ secrets.TEMPLATE_SCRIPT_ID }}
        uses: lucienve/clasp-action@v1.2.1
        with:
          accessToken: ${{ secrets.ACCESS_TOKEN }}
          idToken: ${{ secrets.ID_TOKEN }}
          refreshToken: ${{ secrets.REFRESH_TOKEN }}
          clientId: ${{ secrets.CLIENT_ID }}
          clientSecret: ${{ secrets.CLIENT_SECRET }}
          scriptId: ${{ secrets.TEMPLATE_SCRIPT_ID }}
          command: 'push'
